apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  config.json: |
      {
        "eventsBaseUrl": "{{ .Values.configMap.eventsBaseUrl }}",
        "authServerUrl": "{{ .Values.configMap.authServerUrl }}",
        "providersBaseUrl": "{{ .Values.configMap.providersBaseUrl }}",
        "endpointBase": "{{ .Values.configMap.endpointBase }}",
        "timetableAdminBaseUrl": "{{ .Values.configMap.timetableAdminBaseUrl }}",
        "chouetteBaseUrl": "{{ .Values.configMap.chouetteBaseUrl }}"
      }
