{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: public
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: bel
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- if eq .Values.env "prod"}}
  - host: operator.entur.org
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "app.name" . }}
              port:
                number: {{ .Values.service.http.externalPort }}
  - host: xn--operatr-v1a.entur.org
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "app.name" . }}
              port:
                number: {{ .Values.service.http.externalPort }}
  {{ else }}
  - host: operator.{{ .Release.Namespace }}.entur.org
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "app.name" . }}
              port:
                number: {{ .Values.service.http.externalPort }}
  {{- end}}

{{- end }}
