{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- if eq .Values.env "production"}}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.productionIp }}
    {{ else if eq .Values.env "staging"}}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.stagingIp }}
    {{ else if eq .Values.env "dev"}}
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.devIp }}
    {{- end}}
  name: bel
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  {{- if eq .Values.env "production"}}
  - host: operator.entur.org
    http:
      paths:
        - backend:
            serviceName: {{ template "app.name" . }}
            servicePort: {{ .Values.service.http.externalPort }}
  - host: xn--operatr-v1a.entur.org
    http:
      paths:
        - backend:
            serviceName: {{ template "app.name" . }}
            servicePort: {{ .Values.service.http.externalPort }}
  {{ else }}
  - host: operator.{{ .Release.Namespace }}.entur.org
    http:
      paths:
        - backend:
            serviceName: {{ template "app.name" . }}
            servicePort: {{ .Values.service.http.externalPort }}
  {{- end}}

{{- end }}
