env: dev

configMap:
  endpointBase: /
  eventsBaseUrl: https://api.dev.entur.io/timetable-admin/v1/events/
  providersBaseUrl: https://api.dev.entur.io/timetable-admin/v1/providers/
  timetableAdminBaseUrl: https://api.dev.entur.io/timetable-admin/v1/timetable/
  chouetteBaseUrl: https://rutedb.dev.entur.org/
  udugMicroFrontendUrl: https://netex-validation-reports.dev.entur.org
  auth0Domain: ror-entur-dev.eu.auth0.com
  auth0ClientId: ZFz0whLRMzf8Qk3wjXesHbhtLrvd0zkD
  auth0Audience: https://ror.api.dev.entur.io
  auth0ClaimsNamespace: https://ror.entur.io/role_assignments
  ninsarMicroFrontendUrl: https://line-statistics.dev.entur.org
